### ISSUE TITLE
Gil General:

### ISSUE THREAD

**Issue by daurham** [Team-Droid-SDC/reviews-service#8]
Scan over each of your files and check:
- [x] Remove Comments (Save in separate branch to save notes)
- [x] Keep spacing consistent 
- [x] Consider organizing your dependencies into the right locations (devDep. / dep.)
- [x] Semicolons (add or remove, keep it consistent)
- [x] Add a readMe

Your code is always a pleasure to read Gil. 👏🏼

**Comment by gilcohen67** [comment]
linting:
https://github.com/Team-Droid-SDC/reviews-service/commit/d1426b7ae200d38c129be00a4125282eca555323
deps:
https://github.com/Team-Droid-SDC/reviews-service/commit/4c16e373032410b2298e056c650a7fe0e30f4588
ReadME:
https://github.com/Team-Droid-SDC/reviews-service/commit/c8ef3900bc723afc5e9e2634c18fbffb9f4723be
